all_weapons = [ "hgun_Pistol_heavy_01_F",
                "hgun_ACPC2_F",
                "srifle_DMR_04_F",
                "srifle_DMR_04_Tan_F",
                "srifle_DMR_05_blk_F",
                "srifle_DMR_05_hex_F",
                "srifle_DMR_05_tan_f",
                "srifle_GM6_F",
                "srifle_GM6_camo_F",
                "arifle_Katiba_F",
                "arifle_Katiba_C_F",
                "arifle_Katiba_GL_F",
                "srifle_LRR_F",
                "srifle_LRR_camo_F",
                "srifle_DMR_02_F",
                "srifle_DMR_02_camo_F",
                "srifle_DMR_02_sniper_F",
                "srifle_DMR_03_F",
                "srifle_DMR_03_multicam_F",
                "srifle_DMR_03_khaki_F",
                "srifle_DMR_03_tan_F",
                "srifle_DMR_03_woodland_F",
                "srifle_DMR_06_camo_F",
                "srifle_DMR_06_olive_F",
                "srifle_EBR_F",
		    "arifle_CTAR_blk_F",
		    "arifle_CTAR_GL_blk_F",
		    "CUP_sgun_M1014",
		    "CUP_sgun_Saiga12K",
		    "arifle_MSBS65_black_F",
		    "arifle_MSBS65_GL_F",
                "arifle_Mk20_plain_F",
                "arifle_Mk20_F",
                "arifle_Mk20_GL_plain_F",
                "arifle_Mk20_GL_F",
                "LMG_Mk200_F",
                "arifle_Mk20C_plain_F",
                "arifle_Mk20C_F",
                "arifle_MX_GL_F",
                "arifle_MX_GL_Black_F",
                "arifle_MX_F",
                "arifle_MX_Black_F",
                "arifle_MX_SW_F",
                "arifle_MX_SW_Black_F",
                "arifle_MXC_F",
                "arifle_MXC_Black_F",
                "arifle_MXM_F",
                "arifle_MXM_Black_F",
                "MMG_01_hex_F",
                "MMG_01_tan_F",
                "hgun_P07_F",
                "launch_NLAW_F",
                "hgun_PDW2000_F",
                "srifle_DMR_01_F",
                "hgun_Rook40_F",
                "launch_RPG32_F",
                "arifle_SDAR_F",
                "MMG_02_black_F",
                "MMG_02_camo_F",
                "MMG_02_sand_F",
                "SMG_02_F",
                "launch_B_Titan_short_F",
                "launch_B_Titan_F",
                "arifle_TRG20_F",
                "arifle_TRG21_F",
                "arifle_TRG21_GL_F",
                "SMG_01_F",
                "LMG_Zafir_F",
                "hgun_Pistol_heavy_02_F",
		    "CUP_hgun_Colt1911",
                "launch_O_Titan_short_F",
                "launch_I_Titan_short_F",
                "launch_I_Titan_F",
                "launch_O_Titan_F" ];

all_ammo = [ "10Rnd_338_Mag",
             "130Rnd_338_Mag",
             "7Rnd_408_Mag",
             "11Rnd_45ACP_Mag",
             "30Rnd_45ACP_Mag_SMG_01",
             "6Rnd_45ACP_Cylinder",
             "9Rnd_45ACP_Mag",
             "5Rnd_127x108_Mag",
             "10Rnd_127x54_Mag",
             "5Rnd_127x108_APDS_Mag",
             "3Rnd_HE_Grenade_shell",
             "1Rnd_HE_Grenade_shell",
             "20Rnd_556x45_UW_mag",
             "100Rnd_65x39_caseless_mag",
             "200Rnd_65x39_cased_Box",
             "30Rnd_65x39_caseless_mag",
             "30Rnd_65x39_caseless_green",
             "150Rnd_762x54_Box",
             "20Rnd_762x51_Mag",
             "10Rnd_762x54_Mag",
             "16Rnd_9x21_Mag",
             "30Rnd_9x21_Mag",
             "10Rnd_93x64_DMR_05_Mag",
             "150Rnd_93x64_Mag",
             "NLAW_F",
             "MiniGrenade",
             "HandGrenade",
             "RPG32_HE_F",
             "RPG32_F",
             "Titan_AA",
             "Titan_AP",
             "Titan_AT",
             "30Rnd_556x45_Stanag",
             "ATMine_Range_Mag",
             "Chemlight_blue",
             "Chemlight_green",
             "Chemlight_red",
             "Chemlight_yellow",
             "ClaymoreDirectionalMine_Remote_Mag",
             "SmokeShell",
             "APERSMine_Range_Mag",
		 "CUP_5Rnd_B_Saiga12_Slug",
		 "CUP_12Rnd_B_Saiga12_Buck_00",
		 "30Rnd_65x39_caseless_msbs_mag",
		 "CUP_7Rnd_45ACP_1911",
		 "CUP_8Rnd_12Gauge_Pellets_No00_Buck",
		 "100Rnd_580x42_Mag_F",
		 "IEDUrbanSmall_Remote_Mag" ];				 

all_attach = [ "optic_ACO_grn",
               "optic_Aco",
               "optic_ACO_grn_smg",
               "optic_Aco_smg",
               "optic_AMS",
               "optic_AMS_khk",
               "optic_AMS_snd",
               "optic_Arco",
               "bipod_03_F_blk",
               "bipod_02_F_blk",
               "bipod_01_F_blk",
               "bipod_02_F_hex",
               "bipod_01_F_mtp",
               "bipod_03_F_oli",
               "bipod_01_F_snd",
               "bipod_02_F_tan",
               "optic_DMS",
               "acc_flashlight",
               "acc_pointer_IR",
               "optic_KHS_blk",
               "optic_KHS_hex",
               "optic_KHS_old",
               "optic_KHS_tan",
               "optic_LRPS",
               "optic_Holosight",
               "optic_Holosight_smg",
               "optic_SOS",
               "optic_MRCO",
               "optic_Hamr",
               "muzzle_snds_338_black",
               "muzzle_snds_acp",
               "muzzle_snds_M",
               "muzzle_snds_H",
               "muzzle_snds_B",
               "muzzle_snds_L",
               "muzzle_snds_93mmg",
               "muzzle_snds_H_MG",
               "optic_MRD",
               "muzzle_snds_338_green",
               "muzzle_snds_338_sand",
               "muzzle_snds_93mmg_tan",
               "optic_Yorris",
		   "optic_ico_01_black_f",
		   "optic_ico_01_f" ];			  
				
all_glasses = [ "G_Aviator",
                "G_Balaclava_blk",
                "G_Balaclava_combat",
                "G_Balaclava_lowprofile",
                "G_Balaclava_oli",
                "G_Bandanna_aviator",
                "G_Bandanna_beast",
                "G_Bandanna_blk",
                "G_Bandanna_khk",
                "G_Bandanna_oli",
                "G_Bandanna_shades",
                "G_Bandanna_sport",
                "G_Bandanna_tan",
                "G_Combat",
                "G_Lady_Blue",
                "G_Lady_Dark",
                "G_Lady_Mirror",
                "G_Lady_Red",
                "G_Lowprofile",
                "G_Shades_Black",
                "G_Shades_Blue",
                "G_Shades_Green",
                "G_Shades_Red",
                "G_Spectacles",
                "G_Spectacles_Tinted",
                "G_Sport_Blackred",
                "G_Sport_BlackWhite",
                "G_Sport_Blackyellow",
                "G_Sport_Checkered",
                "G_Sport_Greenblack",
                "G_Sport_Red",
                "G_Squares",
                "G_Squares_Tinted",
                "G_Tactical_Black",
                "G_Tactical_Clear",
                "G_Diving",
		    "CUP_G_ESS_KHK_Facewrap_White" ];
			  
all_misc = [ "MineDetector",
             "Binocular",
             "ItemCompass",
             "FirstAidKit",
             "ItemGPS",
             "ItemMap",
             "Medikit",
             "NVGoggles_OPFOR",
             "NVGoggles",
             "NVGoggles_INDEP",
             "ItemRadio",
             "Rangefinder",
             "ToolKit",
             "ItemWatch"
		
		  ];

west_misc = [ "B_UavTerminal" ];

east_misc = [ "O_UavTerminal" ];
			  
west_uniforms = [ "U_B_CombatUniform_mcam",
                  "U_B_CombatUniform_mcam_tshirt",
                  "U_C_Poloshirt_blue",
                  "U_C_Driver_1_blue",
                  "U_B_FullGhillie_ard",
                  "U_B_FullGhillie_lsh",
                  "U_B_FullGhillie_sard",
                  "U_B_GhillieSuit",
                  "U_B_PilotCoveralls",
                  "U_B_CombatUniform_mcam_vest",
                  "U_B_Protagonist_VR",
                  "U_B_Wetsuit",
                  "U_B_CTRG_1",
			"CUP_U_O_RUS_Ratnik_Winter" ];

east_uniforms = [ "U_C_Poloshirt_burgundy",
                  "U_C_Driver_1_red",
                  "U_O_CombatUniform_ocamo",
                  "U_O_CombatUniform_oucamo",
                  "U_O_FullGhillie_ard",
                  "U_O_FullGhillie_lsh",
                  "U_O_FullGhillie_sard",
                  "U_O_GhillieSuit",
                  "U_O_PilotCoveralls",
                  "U_O_SpecopsUniform_ocamo",
                  "U_O_Protagonist_VR",
                  "U_O_Wetsuit",
                  "U_O_OfficerUniform_ocamo" ];

west_vests = [ "V_HarnessOGL_brn",
               "V_HarnessO_brn",
               "V_RebreatherB",
               "V_PlateCarrier1_blk",
               "V_Chestrig_blk",
               "V_Chestrig_khk",
               "V_BandollierB_cbr",
               "V_BandollierB_khk",
               "V_PlateCarrier1_rgr",
               "V_Chestrig_rgr",
               "V_Chestrig_oli",
               "V_HarnessOGL_gry",
               "V_HarnessO_gry",
               "V_BandollierB_blk",
               "V_BandollierB_rgr",
               "V_BandollierB_oli",
		   "CUP_V_PMC_CIRAS_Winter_Patrol" ];

east_vests = [ "V_HarnessOGL_gry",
               "V_HarnessO_gry",
               "V_RebreatherIR",
               "V_Chestrig_rgr",
               "V_Chestrig_oli",
               "V_BandollierB_rgr",
               "V_BandollierB_oli",
               "V_Chestrig_blk",
               "V_Chestrig_khk",
               "V_HarnessOGL_brn",
               "V_HarnessO_brn",
               "V_BandollierB_blk",
               "V_BandollierB_cbr",
               "V_BandollierB_khk" ];

west_helmets = [ "H_Cap_tan_specops_US",
                 "H_HelmetCrew_B",
                 "H_CrewHelmetHeli_B",
                 "H_PilotHelmetHeli_B",
                 "H_MilCap_mcamo",
                 "H_PilotHelmetFighter_B",
                 "H_StrawHat",
                 "H_Cap_blu",
                 "H_RacingHelmet_1_blue_F",
                 "H_ShemagOpen_tan",
                 "H_HelmetSpecB_sand",
                 "H_HelmetSpecB_snakeskin",
                 "H_HelmetB_light",
                 "H_ShemagOpen_khk",
		     "CUP_H_RUS_6B47_v2_Winter" ];

east_helmets = [ "H_Cap_brn_SPECOPS",
                 "H_HelmetCrew_O",
                 "H_CrewHelmetHeli_O",
                 "H_PilotHelmetHeli_O",
                 "H_MilCap_ocamo",
                 "H_PilotHelmetFighter_O",
                 "H_HelmetO_ocamo",
                 "H_HelmetO_oucamo",
                 "H_StrawHat_dark",
                 "H_Cap_red",
                 "H_RacingHelmet_1_red_F",
                 "H_Shemag_olive" ];


west_packs = [ "B_AssaultPack_rgr",
               "B_AssaultPack_mcamo",
               "B_Carryall_khk",
               "B_Carryall_mcamo",
               "B_FieldPack_cbr",
               "B_FieldPack_khk",
               "B_TacticalPack_rgr",
               "B_TacticalPack_mcamo",
               "B_Parachute",
               "B_AssaultPack_blk",
               "B_AssaultPack_cbr",
               "B_AssaultPack_dgtl",
               "B_AssaultPack_khk",
               "B_AssaultPack_sgg",
               "B_Carryall_cbr",
               "B_Carryall_oli",
               "B_FieldPack_blk",
               "B_FieldPack_oli",
               "B_Kitbag_cbr",
               "B_Kitbag_mcamo",
               "B_Kitbag_sgg",
               "B_TacticalPack_blk",
               "B_TacticalPack_oli",
		   "B_CivilianBackpack_01_Everyday_IDAP_F" ];


east_packs = [ "B_AssaultPack_blk",
               "B_AssaultPack_ocamo",
               "B_Carryall_ocamo",
               "B_Carryall_oucamo",
               "B_FieldPack_ocamo",
               "B_FieldPack_oucamo",
               "B_Kitbag_rgr",
               "B_Parachute",
               "B_TacticalPack_blk",
               "B_TacticalPack_ocamo",
               "B_AssaultPack_cbr",
               "B_AssaultPack_dgtl",
               "B_AssaultPack_rgr",
               "B_AssaultPack_khk",
               "B_AssaultPack_sgg",
               "B_Carryall_cbr",
               "B_Carryall_khk",
               "B_FieldPack_cbr",
               "B_FieldPack_oli",
               "B_Kitbag_cbr",
               "B_Kitbag_sgg",
               "B_TacticalPack_rgr",
               "B_TacticalPack_oli" ];

west_glasses = [ "G_B_Diving" ];
east_glasses = [ "G_O_Diving" ];
				

